// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzv7y6x4qWM8-3N-1BD27ZcJyRjYfm6lw',
    appId: '1:119630417706:web:49ece9796319b9fb251853',
    messagingSenderId: '119630417706',
    projectId: 'airbnbproject-e9e93',
    authDomain: 'airbnbproject-e9e93.firebaseapp.com',
    storageBucket: 'airbnbproject-e9e93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKO7IFptMQiB4htGvaS1ROxI5_9PikzGw',
    appId: '1:119630417706:android:6055c433c55894b5251853',
    messagingSenderId: '119630417706',
    projectId: 'airbnbproject-e9e93',
    storageBucket: 'airbnbproject-e9e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFXrK8QgtAtO7OQGDTw89wmOp_bmRM2s',
    appId: '1:119630417706:ios:e70e3e851e0380a7251853',
    messagingSenderId: '119630417706',
    projectId: 'airbnbproject-e9e93',
    storageBucket: 'airbnbproject-e9e93.firebasestorage.app',
    iosBundleId: 'com.example.airbnbproject',
  );
}
